{{- if .Values.server.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homelab-autodoc.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homelab-autodoc.server.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
